name: Auto updating PKGBUILD - Parallel Uploading
on:
  schedule:
    -  cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  buildAUR:
    strategy:
        matrix:
            repos: [
                firefox-nightly-bin,
            ]
        fail-fast: false
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: 'vifly/arch-build'
      - name: configure pgp server
        run: |
          sed -i '22i mkdir -p /home/builder/.gnupg' ./build-aur-action/entrypoint.sh
          sed -i '23i sudo --set-home -u builder echo "keyserver hkps://keys.openpgp.org" > /home/builder/.gnupg/gpg.conf' ./build-aur-action/entrypoint.sh
          sed -i '24i chown -R builder:builder' ./build-aur-action/entrypoint.sh
          sed -i '25i cat /home/builder/.gnupg/gpg.conf' ./build-aur-action/entrypoint.sh
          cat ./build-aur-action/entrypoint.sh
      - uses: ./build-aur-action
        with:
          repo-name: ${{ matrix.repos }}
    
      - uses: actions/upload-artifact@v4
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.repos }}
          if-no-files-found: error
