name: Auto updating PKGBUILD - Serial uploading
on:
  schedule:
    -  cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  prepare:
    name: get new pkgver
    runs-on: ubuntu-latest
    outputs:
      pkgver: ${{ steps.get-new-pkgver.outputs.pkgver }}
      version: ${{ steps.get-new-pkgver.outputs.version }}
    steps:
    -   name: get new pkgver
        id: get-new-pkgver
        run: |
          _url=https://ftp.mozilla.org/pub/firefox/nightly
          _version=$(curl "${CURL_OPTS[@]}" ${_url}/latest-mozilla-central-l10n/linux-x86_64/xpi/ | grep "ach.langpack.xpi" | sed "s/^.*>firefox-//; s/\.ach.*//" | sort -n | tail -n 1)
          _build_id_raw="$(curl -s "${_url}/latest-mozilla-central-l10n/firefox-${_version}.ach.linux-x86_64.checksums" | grep '.partial.mar' | cut -d' ' -f4 | grep -E -o '[[:digit:]]{14}' | sort | tail -n1)"
          declare -A _build_id
          _build_id=(
            [year]="${_build_id_raw:0:4}"
            [month]="${_build_id_raw:4:2}"
            [day]="${_build_id_raw:6:2}"
            [hour]="${_build_id_raw:8:2}"
            [min]="${_build_id_raw:10:2}"
            [sec]="${_build_id_raw:12:2}"
            [date]="${_build_id_raw:0:8}"
            [time]="${_build_id_raw:8:6}"
          )
          _build_id_date=${_build_id[date]}
          _build_id_time=${_build_id[time]}
          echo "version=${_version}" >> "${GITHUB_OUTPUT}"
          echo "pkgver=$(printf "%s.%s.%s" ${_version} ${_build_id_date} ${_build_id_time})" >> "${GITHUB_OUTPUT}"
  update_oth_lang:
    runs-on: ubuntu-latest
    needs: prepare
    container: archlinux
    steps:
      -   name: Install dependencies and update
          run: pacman -Syu --noconfirm --noprogressbar --needed base-devel git pacman-contrib
      -   uses: actions/checkout@v4
          with:
            fetch-depth: 0
      -   name: create user for further steps
          run: |
            useradd builder -m
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            chmod -R a+rw .
            pwd
      -   name: upd
          run: sudo -Eu builder sh ./.github/workflows/update-pkgbuild-lang.sh
      -   name: debug
          run: |
            pwd
            ls -laZ
      -   uses: actions/upload-artifact@v4
          with:
            name: new_ver_of_PKGBUILD
            path: |
              firefox-nightly-i18n/
  push_updates:
    runs-on: ubuntu-latest
    needs: [ prepare, update_oth_lang ]
    steps:
    -   uses: actions/checkout@v4
    -   name: remove old ver
        run: rm -rf firefox-nightly-i18n/*
    -   uses: actions/download-artifact@v4
        with:
          name: new_ver_of_PKGBUILD
          path: firefox-nightly-i18n/
    -   uses: actions-js/push@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "update to ${{ needs.prepare.outputs.pkgver }}"
          branch: main
  publish_to_aur:
    runs-on: ubuntu-latest
    container: archlinux
    needs: [ update_oth_lang,prepare ]
    steps:
    -   name: instll deps
        run: |
          pacman -Syu --noconfirm --needed --overwrite '*' openssh sudo base-devel git fakeroot binutils gcc awk binutils xz libarchive bzip2 coreutils file findutils gettext grep gzip sed ncurses util-linux pacman-contrib debugedit
    -   uses: actions/checkout@v4
    -   name: config ssh
        run: |
          #!/bin/bash
          set -o errexit -o pipefail -o nounset
          echo '::group::Creating builder user'
          useradd --create-home --shell /bin/bash builder
          passwd --delete builder
          mkdir -p /etc/sudoers.d/
          echo "builder  ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/builder
          echo '::endgroup::'
          echo '::group::Initializing SSH directory'
          mkdir -pv /home/builder/.ssh
          touch /home/builder/.ssh/known_hosts
          cp -v ./.github/workflows/ssh_config /home/builder/.ssh/config
          chown -vR builder:builder /home/builder
          chmod -vR 600 /home/builder/.ssh/*
          echo '::endgroup::'
          sudo -Eu builder sh ./.github/workflows/config_ssh.sh "${{secrets.AUR_SSH_PRIVATE_KEY}}"
    -   name: rm old files
        run: rm -rf ./firefox-nightly-i18n/
    -   uses: actions/download-artifact@v4
        with:
          name: new_ver_of_PKGBUILD
          path: firefox-nightly-i18n/
    -   name: publish
        run: sudo -Eu builder sh ./.github/workflows/publish2aur.sh
  buildAUR:
    needs: publish_to_aur
    strategy:
      matrix:
        repos: [
          firefox-nightly-i18n-ach,
          firefox-nightly-i18n-af,
          firefox-nightly-i18n-an,
          firefox-nightly-i18n-ar,
          firefox-nightly-i18n-ast,
          firefox-nightly-i18n-az,
          firefox-nightly-i18n-be,
          firefox-nightly-i18n-bg,
          firefox-nightly-i18n-bn,
          firefox-nightly-i18n-br,
          firefox-nightly-i18n-bs,
          firefox-nightly-i18n-ca-valencia,
          firefox-nightly-i18n-ca,
          firefox-nightly-i18n-cak,
          firefox-nightly-i18n-cs,
          firefox-nightly-i18n-cy,
          firefox-nightly-i18n-da,
          firefox-nightly-i18n-de,
          firefox-nightly-i18n-dsb,
          firefox-nightly-i18n-el,
          firefox-nightly-i18n-en-ca,
          firefox-nightly-i18n-en-gb,
          firefox-nightly-i18n-eo,
          firefox-nightly-i18n-es-ar,
          firefox-nightly-i18n-es-cl,
          firefox-nightly-i18n-es-es,
          firefox-nightly-i18n-es-mx,
          firefox-nightly-i18n-et,
          firefox-nightly-i18n-eu,
          firefox-nightly-i18n-fa,
          firefox-nightly-i18n-ff,
          firefox-nightly-i18n-fi,
          firefox-nightly-i18n-fr,
          firefox-nightly-i18n-fy-nl,
          firefox-nightly-i18n-ga-ie,
          firefox-nightly-i18n-gd,
          firefox-nightly-i18n-gl,
          firefox-nightly-i18n-gn,
          firefox-nightly-i18n-gu-in,
          firefox-nightly-i18n-he,
          firefox-nightly-i18n-hi-in,
          firefox-nightly-i18n-hr,
          firefox-nightly-i18n-hsb,
          firefox-nightly-i18n-hu,
          firefox-nightly-i18n-hy-am,
          firefox-nightly-i18n-ia,
          firefox-nightly-i18n-id,
          firefox-nightly-i18n-is,
          firefox-nightly-i18n-it,
          firefox-nightly-i18n-ja,
          firefox-nightly-i18n-ka,
          firefox-nightly-i18n-kab,
          firefox-nightly-i18n-kk,
          firefox-nightly-i18n-km,
          firefox-nightly-i18n-kn,
          firefox-nightly-i18n-ko,
          firefox-nightly-i18n-lij,
          firefox-nightly-i18n-lt,
          firefox-nightly-i18n-lv,
          firefox-nightly-i18n-mk,
          firefox-nightly-i18n-mr,
          firefox-nightly-i18n-ms,
          firefox-nightly-i18n-my,
          firefox-nightly-i18n-nb-no,
          firefox-nightly-i18n-ne-np,
          firefox-nightly-i18n-nl,
          firefox-nightly-i18n-nn-no,
          firefox-nightly-i18n-oc,
          firefox-nightly-i18n-pa-in,
          firefox-nightly-i18n-pl,
          firefox-nightly-i18n-pt-br,
          firefox-nightly-i18n-pt-pt,
          firefox-nightly-i18n-rm,
          firefox-nightly-i18n-ro,
          firefox-nightly-i18n-ru,
          firefox-nightly-i18n-si,
          firefox-nightly-i18n-sk,
          firefox-nightly-i18n-sl,
          firefox-nightly-i18n-son,
          firefox-nightly-i18n-sq,
          firefox-nightly-i18n-sr,
          firefox-nightly-i18n-sv-se,
          firefox-nightly-i18n-ta,
          firefox-nightly-i18n-te,
          firefox-nightly-i18n-th,
          firefox-nightly-i18n-tl,
          firefox-nightly-i18n-tr,
          firefox-nightly-i18n-trs,
          firefox-nightly-i18n-uk,
          firefox-nightly-i18n-ur,
          firefox-nightly-i18n-uz,
          firefox-nightly-i18n-vi,
          firefox-nightly-i18n-xh,
          firefox-nightly-i18n-zh-cn,
          firefox-nightly-i18n-zh-tw,
          firefox-nightly-bin,
          visual-studio-code-insiders-bin
        ]
      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with: 
        repository: 'vifly/arch-build'
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: actions/upload-artifact@v4
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error
  uploadToRemote:
    strategy:
      matrix:
        remote: [ onedrive, r2 ]
    runs-on: ubuntu-latest
    needs: [buildAUR]

    steps:
      - uses: actions/checkout@v4
        with: 
          repository: 'vifly/arch-build'
      
      - uses: actions/download-artifact@v4
        id: download

      - name: Display structure of downloaded files
        run: ls -R ${{ steps.download.outputs.download-path }}
      
      - uses: ./create-db-and-upload-action
        with:
          RCLONE_CONFIG_CONTENT: ${{secrets.RCLONE_CONFIG}}
          RCLONE_CONFIG_NAME: ${{matrix.remote}}
          dest_path: /repo/archlinux/
          repo_name: archlinux-sving1024
          gpg-privatekey: ${{ secrets.gpg_private_key }}
          local_path: ${{ steps.download.outputs.download-path }}
      
