name: Auto updating PKGBUILD
on:
  push
jobs:
  update_PKGBUILD:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
    -   uses: actions/checkout@v4
    -   name: Install dependencies and update
        run: pacman -Syu --noconfirm --noprogressbar --needed base-devel git pacman-contrib
    -   name: update pkgver
        working-directory: firefox-nightly-i18n
        run: |
          ls
          _url=https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/linux-x86_64/xpi
          _version=$(curl "${CURL_OPTS[@]}" ${_url}/ | grep "ach.langpack.xpi" | sed "s/^.*>firefox-//; s/\.ach.*//" | sort -n | tail -n 1)
          sed -i "s/pkgver=.*$/pkgver=${_version}/" PKGBUILD
          cat PKGBUILD
    -   name: update the sha256sum in PKGBUILD
        working-directory: firefox-nightly-i18n
        run: |
          updpkgsums
          rm -rf ./firefox-*
    -   name: generate .SRCINFO
        working-directory: firefox-nightly-i18n
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chmod -R a+rw .
          sudo -Eu builder makepkg --printsrcinfo > .SRCINFO
          